# Generated by Django 5.1.1 on 2026-08-25 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('badge_text', models.CharField(default='5-Day Workshop', max_length=100)),
                ('short_description', models.TextField()),
                ('detailed_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('image_path', models.CharField(blank=True, help_text='Fallback static image path e.g. images/fullstack.svg', max_length=255, null=True)),
                ('duration', models.CharField(default='5 Days (Intensive Sessions)', max_length=100)),
                ('who_can_attend', models.TextField(default='Students from any stream interested in technology.')),
                ('requirements', models.TextField(default='Basic computer knowledge, Laptop recommended')),
                ('capstone_title', models.CharField(blank=True, max_length=200)),
                ('capstone_description', models.TextField(blank=True)),
                ('capstone_tech_flow', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreviousEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('image_path', models.CharField(blank=True, help_text='Fallback static image path e.g. images/cs50p.svg', max_length=255, null=True)),
                ('date_str', models.CharField(default='2025 – 2026', max_length=100)),
                ('year', models.CharField(default='2026', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('college_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('stream', models.CharField(choices=[('BCA', 'BCA'), ('B.Com', 'B.Com'), ('BBA', 'BBA'), ('B.Com A/F', 'B.Com A/F'), ('B.Com Logistics', 'B.Com Logistics'), ('B.Com with CA', 'B.Com with CA')], max_length=50)),
                ('course', models.CharField(choices=[('Full Stack Development', 'Full Stack Development'), ('Data Analytics', 'Data Analytics')], max_length=100)),
                ('year_of_study', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=50)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], max_length=10)),
                ('has_laptop', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(default='Chathurya Student Developers Club', max_length=200)),
                ('college_name', models.CharField(default='Tech Campus, College Block B', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('hero_title', models.CharField(default='Learn. Build. Launch.', max_length=200)),
                ('hero_subtitle', models.TextField(default='Welcome to Chathurya Student Developers Club. Join our hands-on technical workshops designed to help students build practical skills, explore modern software technologies, and launch real-world projects.')),
                ('about_text', models.TextField(default='Chathurya Student Developers Club is a premier student-led technical community dedicated to nurturing coding talent, practical software engineering, and data science skills.')),
                ('contact_email', models.EmailField(default='chathurya.club@college.edu', max_length=254)),
                ('contact_phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('address', models.TextField(default='Tech Building Block B, Innovation Way, College Campus, 560100')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com')),
                ('github_url', models.URLField(blank=True, default='https://github.com')),
                ('footer_text', models.TextField(default='Official Student Technical & Developer Community dedicated to practical coding bootcamps, workshops, and student tech growth.')),
                ('copyright_text', models.CharField(default='© 2026 Chathurya Student Developers Club. All Rights Reserved.', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='CourseProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workshop.course')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.CharField(max_length=20)),
                ('section_title', models.CharField(max_length=200)),
                ('bullets', models.TextField(help_text='Enter bullet points separated by newlines')),
                ('display_order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='workshop.course')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
