# Generated by Django 5.2.17 on 2026-08-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='course',
            field=models.CharField(choices=[('', 'Select Course'), ('Full Stack Development', 'Full Stack Development'), ('Data Analytics', 'Data Analytics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='has_laptop',
            field=models.CharField(choices=[('', 'Select Laptop Availability'), ('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='section',
            field=models.CharField(choices=[('', 'Select Section'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='stream',
            field=models.CharField(choices=[('', 'Select Stream'), ('BCA', 'BCA'), ('B.Com', 'B.Com'), ('BBA', 'BBA'), ('B.Com A/F', 'B.Com A/F'), ('B.Com Logistics', 'B.Com Logistics'), ('B.Com with CA', 'B.Com with CA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='year_of_study',
            field=models.CharField(choices=[('', 'Select Year of Study'), ('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=50),
        ),
    ]
