# Generated by Django 5.2.17 on 2026-08-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_registration_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='year_of_study',
            field=models.CharField(choices=[('', 'Select Year of Study'), ('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year')], max_length=50),
        ),
    ]
