# Generated by Django 5.1.1 on 2026-08-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_alter_sitesettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='approval_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='notification_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='registration',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='notification_status',
            field=models.CharField(choices=[('Not Sent', 'Not Sent'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Not Sent', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='notification_type',
            field=models.CharField(choices=[('None', 'None'), ('Approval', 'Approval'), ('Rejection', 'Rejection')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='rejection_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
