# Generated by Django 5.2.17 on 2026-08-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_alter_sitesettings_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDayStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('session_day', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['session_day'],
                'unique_together': {('course_name', 'session_day')},
            },
        ),
    ]
