# Generated by Django 5.1.1 on 2026-08-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_registration_approval_email_sent_and_more'),
        ('workshop', '0005_sessiondaystatus'),
    ]

    operations = [
    ]
